### PR TITLE
Fixes overwriting filterparameters ( #5 )

### LINKED ISSUE #5: Overwriting filterparameters not possible
I have a filter with a `Simple lookup` based on a `tags` attribute. In the MM core list, i can overwrite the filter parameter but in the layer definition not.

### PR DESCRIPTION
**Pull request by cliffparnitzky**
Fixes #5

### CODE REVIEW

File: src/Resources/contao/dca/tl_leaflet_layer.php [hunk 1]
```diff
@@ -14,6 +15,9 @@
 
 use MetaModels\CoreBundle\Contao\Hooks\ContentElementCallback;
```
Comment (cliffparnitzky) [inline src/Resources/contao/dca/tl_leaflet_layer.php]: The `ContentElementCallback` could be removed and all calls can be replaced with the `LeafletLayerCallback` because they have the same has the same parent class.

Comment (cliffparnitzky) [reply src/Resources/contao/dca/tl_leaflet_layer.php]: fixed with 65a8871f25cdd2ab82c1420dccda84309b166147

File: src/Contao/Hooks/LeafletLayerCallback.php [hunk 2]
```diff
@@ -0,0 +1,40 @@
...
+     *
+     * @param \DC_Table $dataContainer The data container calling this method.
+     *
+     * @return void
+     */
+    public function buildFilterParameterList(\DC_Table $dataContainer)
+    {
+        parent::buildFilterParamsFor($dataContainer, 'metamodels');
+    }
+}
```
Comment (dmolineus) [inline src/Contao/Hooks/LeafletLayerCallback.php]: Please add a new line here.

File: src/DependencyInjection/NetzmachtContaoLeafletMetaModelsExtension.php [hunk 3]
```diff
@@ -29,13 +31,19 @@ final class NetzmachtContaoLeafletMetaModelsExtension extends Extension
...
-        $loader->load('listeners.xml');
-        $loader->load('services.xml');
+        $xmlLoader->load('listeners.xml');
+        $xmlLoader->load('services.xml');
+        
+        $ymlLoader = new YamlFileLoader(
+            $container,
+            new FileLocator(__DIR__.'/../Resources/config')
+        );
+        $ymlLoader->load('hooks.yml');
```
Comment (dmolineus) [inline src/DependencyInjection/NetzmachtContaoLeafletMetaModelsExtension.php]: Please use the existing `listeners.xml` to register new hook listeners.

File: src/MapLayer/MetaModelsLayerMapper.php [hunk 4]
```diff
@@ -286,7 +287,7 @@ private function getItems(MetaModel $metaModel, LayerModel $model): Items
         $filterSetting->addRules(
             $metaModelFilter,
             array_merge(
-                StringUtil::deserialize($model->metamodel_filteraprams, true),
+                StringUtil::deserialize($model->metamodel_filterparams, true),
```
Comment (dmolineus) [inline src/MapLayer/MetaModelsLayerMapper.php:290]: Nice catch.

File: src/Resources/config/hooks.yml [hunk 5]
```diff
@@ -0,0 +1,3 @@
+services:
```
Comment (dmolineus) [inline src/Resources/config/hooks.yml]: Please use the `listeners.xml` and remove the `hooks.yml` again.

File: src/Resources/contao/languages/de/tl_leaflet_layer.php [hunk 6]
```diff
@@ -12,19 +12,19 @@
...
+$GLOBALS['TL_LANG']['tl_leaflet_layer']['metamodel_sortby']['0']               = 'Sortieren nach';
+$GLOBALS['TL_LANG']['tl_leaflet_layer']['metamodel_sortby']['1']               = 'Bitte wählen Sie die Sortierreihenfolge aus.';
+$GLOBALS['TL_LANG']['tl_leaflet_layer']['metamodel_sortby_direction']['0']     = 'Nach Richtung sortieren';
+$GLOBALS['TL_LANG']['tl_leaflet_layer']['metamodel_sortby_direction']['1']     = 'Nach aufsteigender oder absteigender Reihenfolge  sortieren.';
+$GLOBALS['TL_LANG']['tl_leaflet_layer']['metamodel_use_limit']['0']            = 'Offset und Limit für die Auflistung verwenden.';
+$GLOBALS['TL_LANG']['tl_leaflet_layer']['metamodel_use_limit']['1']            = 'Auswählen, falls Sie die Anzahl anzuzeigender Datensätze begrenzen möchten. Diese Einstellung ist beispielsweise nützlich, wenn Sie nur die ersten 500 Datensätze anzeigen möchten, oder falls Sie alle Datensätze anzeigen und dabei die ersten 10 überspringen wollen. Eine voreingestellte Paginierung bleibt dabei erhalten.';
```
Comment (dmolineus) [inline src/Resources/contao/languages/de/tl_leaflet_layer.php]: German translation are managed at transifex, to these changes will get lost.

File: src/Contao/Hooks/LeafletLayerCallback.php [hunk 7]
```diff
@@ -0,0 +1,40 @@
...
+    protected static $tableName = 'tl_leaflet_layer';
+
+    /**
+     * Called from tl_content.onload_callback.
+     *
+     * @param \DC_Table $dataContainer The data container calling this method.
+     *
+     * @return void
+     */
+    public function buildFilterParameterList(\DC_Table $dataContainer)
```
Comment (dmolineus) [inline src/Contao/Hooks/LeafletLayerCallback.php]: Please use the more abstract `\Contao\DataContainer` class as type hint as Contao uses it in its documentation.

File: src/Contao/Hooks/LeafletLayerCallback.php [hunk 8]
```diff
@@ -0,0 +1,40 @@
...
+ * Contao Leaflet MetaModels integration.
+ *
+ * @package    contao-leaflet-metamodels
+ * @author     Cliff Parnitzky <contao@cliff-parnitzky.de>
+ * @copyright  2015-2020 netzmacht David Molineus
+ * @license    LGPL 3.0-or-later https://github.com/netzmacht/contao-leaflet-metamodels/blob/master/LICENSE
+ * @filesource MetaModels\CoreBundle\Contao\Hooks\ModuleCallback
+ */
+
+namespace Netzmacht\Contao\Leaflet\MetaModels\Contao\Hooks;
```
Comment (dmolineus) [inline src/Contao/Hooks/LeafletLayerCallback.php]: Please follow the existing naming convention. First of all, the class does not handle hooks but callbacks. Furthermore, both (hooks and dcs callback) are threated as listeners. A dca listener should live withing the namespace `Netzmacht\Contao\Leaflet\MetaModels\EventListener\Dca`.

File: src/Contao/Hooks/LeafletLayerCallback.php [hunk 9]
```diff
@@ -0,0 +1,40 @@
...
+
+use MetaModels\CoreBundle\Contao\Hooks\AbstractContentElementAndModuleCallback;
+
+/**
+ * This class provides callbacks for tl_module.
+ */
+class LeafletLayerCallback extends AbstractContentElementAndModuleCallback
```
Comment (dmolineus) [inline src/Contao/Hooks/LeafletLayerCallback.php]: I use the naming convention of `[CamelizedTableName]DcaListener` for the class listener. The name is used already and also required the inheritance of a parent class. So I suggest do rename it to `MetaModelsLeafletLayerDcaListener` instead.

**Review by dmolineus — CHANGES_REQUESTED** [review]
Thanks for providing this PR. I added some request for changes, mostly nitpicking for naming and code conventions.

File: src/Resources/contao/languages/de/tl_leaflet_layer.php (hunk 6 above)
Comment (cliffparnitzky) [reply src/Resources/contao/languages/de/tl_leaflet_layer.php]: Can't find the project at transifex. If you add me, I will transfer the translations.

**Comment by cliffparnitzky** [comment]
Generally i used the structure and convention of MetaModels ... hope I can transfer it to your structure and convention.

File: src/Contao/Hooks/LeafletLayerCallback.php (hunk 7 above)
Comment (cliffparnitzky) [reply src/Contao/Hooks/LeafletLayerCallback.php]: Fixed

File: src/Contao/Hooks/LeafletLayerCallback.php (hunk 2 above)
Comment (cliffparnitzky) [reply src/Contao/Hooks/LeafletLayerCallback.php]: fixed

File: src/Contao/Hooks/LeafletLayerCallback.php (hunk 9 above)
Comment (cliffparnitzky) [reply src/Contao/Hooks/LeafletLayerCallback.php]: Renamed `Netzmacht\Contao\Leaflet\MetaModels\Contao\Hooks\LeafletLayerCallback` to `Netzmacht\Contao\Leaflet\MetaModels\EventListener\Dca\MetaModelsLeafletLayerDcaListener`

File: src/Contao/Hooks/LeafletLayerCallback.php (hunk 8 above)
Comment (cliffparnitzky) [reply src/Contao/Hooks/LeafletLayerCallback.php]: Renamed `Netzmacht\Contao\Leaflet\MetaModels\Contao\Hooks\LeafletLayerCallback` to `Netzmacht\Contao\Leaflet\MetaModels\EventListener\Dca\MetaModelsLeafletLayerDcaListener`

File: src/Resources/config/hooks.yml (hunk 5 above)
Comment (cliffparnitzky) [reply src/Resources/config/hooks.yml]: Removed the file

File: src/DependencyInjection/NetzmachtContaoLeafletMetaModelsExtension.php (hunk 3 above)
Comment (cliffparnitzky) [reply src/DependencyInjection/NetzmachtContaoLeafletMetaModelsExtension.php]: Moved definition to `listeners.xml`

**Comment by cliffparnitzky** [comment]
Hopefully fixed the code correct. Finaly I need access via transiofex to add the german translations.

**Comment by cliffparnitzky** [comment]
@dmolineus Are there any other open rewiew than the translation issue?

**Comment by cliffparnitzky** [comment]
@dmolineus Are there any other open rewiew than the translation issue?

**Comment by zonky2** [comment]
@cliffparnitzky Transifex: https://www.transifex.com/netzmacht/contao-leaflet-maps/

File: src/Resources/contao/languages/de/tl_leaflet_layer.php (hunk 6 above)
Comment (zonky2) [reply src/Resources/contao/languages/de/tl_leaflet_layer.php]: @cliffparnitzky the resource is here https://www.transifex.com/netzmacht/contao-leaflet-maps/translate/#de/metamodels-tl_leaflet_layer

You should ony add the new `$GLOBALS['TL_LANG']['tl_leaflet_layer']['metamodel_filterparams_use_get']['0']` and add a blank line at least

delete the changes at `de`

File: src/DependencyInjection/NetzmachtContaoLeafletMetaModelsExtension.php [hunk 10]
```diff
@@ -29,13 +30,13 @@ final class NetzmachtContaoLeafletMetaModelsExtension extends Extension
      */
     public function load(array $configs, ContainerBuilder $container): void
     {
-        $loader = new XmlFileLoader(
+        $xmlLoader = new XmlFileLoader(
```
Comment (zonky2) [inline src/DependencyInjection/NetzmachtContaoLeafletMetaModelsExtension.php]: @cliffparnitzky is it absolutely necessary to rename the variable?

Comment (cliffparnitzky) [reply src/DependencyInjection/NetzmachtContaoLeafletMetaModelsExtension.php]: No, was part of development when there was another loader. I've changed it.

File: src/Resources/contao/languages/de/tl_leaflet_layer.php (hunk 6 above)
Comment (cliffparnitzky) [reply src/Resources/contao/languages/de/tl_leaflet_layer.php]: Reverted the german language file and added a blank line at the end of the english one.

**Review by zonky2 — APPROVED** [review]
LGTM

**Comment by dmolineus** [comment]
Thanks @cliffparnitzky and sorry for the long outstanding response
